### ISSUE TITLE
What is the correct way to run this?

### ISSUE THREAD

**Issue by eabase** [albertomercurio/covid-19_italy#1]
Mysterious
```
$ python.exe covid19_italy.py
Traceback (most recent call last):
  File "covid19_italy.py", line 8, in <module>
    import geopandas as gpd
  File "C:\Python37\lib\site-packages\geopandas\__init__.py", line 5, in <module>
    from geopandas.io.file import read_file  # noqa
  File "C:\Python37\lib\site-packages\geopandas\io\file.py", line 6, in <module>
    import fiona
  File "C:\Python37\lib\site-packages\fiona\__init__.py", line 87, in <module>
    from fiona.collection import BytesCollection, Collection
  File "C:\Python37\lib\site-packages\fiona\collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: DLL load failed: The specified procedure could not be found.
```

**Comment by albertomercurio** [comment]
Hello,
you have to install some python libraries like:
Geopandas
Numpy
Pandas
Scipy
Matplotlib
Mapclassify

I suggest to run it in Linux Ubuntu 18.04 with python3, but it should run
in any system.
If you have windows, you have to install wget also:
https://builtvisible.com/download-your-website-with-wget/

I hope I satisfied you request,
Best regards,
Alberto

Il ven 27 mar 2020, 01:11 eabase <notifications@github.com> ha scritto:
