### ISSUE TITLE
Keep getting this error

### ISSUE THREAD

**Issue by buldus2** [albertomercurio/covid-19_italy#2]
Hello. GREAT JOB first of all.
I installed all the needed packages, but I still get this error and I can't figure out why. Could you please give me some advice? I run Python3 on MacOS Catalina. It calculates correctly all the variables of the equations, but then it looks like it has a problem saving the image file.

Traceback (most recent call last):
  File "/Users/PFB/Downloads/covid-19_italy-master/covid19_italy.py", line 303, in <module>
    plt.savefig('img_italia/'+str(date)+"_1.png",dpi=200,bbox_inches='tight')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/pyplot.py", line 723, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/figure.py", line 2203, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2098, in print_figure
    result = print_method(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 535, in print_png
    with cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 418, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 403, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'img_italia/2020-03-28_1.png'

**Comment by albertomercurio** [comment]
I think it's a problem of MacOS. Try to specify the full path, for example
`plt.savefig('/Users/username/covid-19_italy/img_italia/'+str(date)+"_1.png",dpi=200,bbox_inches='tight')`
replacing it with the real path.
Repeat this to all savefig commands.

**Comment by buldus2** [comment]
Grazie per la risposta (posso scriverti in Italiano?) 
mi domando anche se c'è la possibilità di conoscere il valore stimato del giorno o dei giorni successivi nei vari modelli (SIR mod e Richards) oppure è solo una rappresentazione grafica?

**Comment by albertomercurio** [comment]
Certo. Una volta fatto il fit, la variabile popt contiene i parametri fittati. Quindi basta utilizzare il comando `richards(x,*popt)` o `sir(x,*popt)` dove x è il giorno in cui vuoi calcolare gli infetti.

**Comment by buldus2** [comment]
ora funziona anche il salvataggio dei file. Errore mio! Stupendo, grazie.
L'ultima cosa, se posso: facendo sir(x, *popt) con x=33 mi dà credo il valore di domani, mentre con le altre funzioni qualunque x metta mi dà risultati molto bassi (e all'aumentare della x arriva a 15.000 o 22.000, non di più). C'è sicuramente qualcosa che sbaglio banalmente. 
Sai cosa può essere? funziona bene solo con SIR, le altre funzioni no :(

grazie mille sei davvero gentile

**Comment by albertomercurio** [comment]
Devi mettere il comando subito dopo il fit degli infetti, non dopo quello dei deceduti. Perché la variabile popt cambia sempre.

**Comment by buldus2** [comment]
Hai perfettamente ragione. Ora funziona tutto.
Ti ringrazio molto per la tua disponibilità e celerità con cui hai risposto. Davvero un eccellente lavoro.
